version: "3.8"

services:
  db:
    image: mongo:latest
    hostname: db
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1.8GB"

  api01:
    build: .
    hostname: api01
    depends_on:
      - db
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.35GB"

  api02:
    build: .
    hostname: api02
    depends_on:
      - db
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.35GB"

  nginx:
    image: nginx:latest
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "0.5GB"

networks:
  default:
    driver: bridge
    name: rinha
